### ISSUE TITLE
Machining Rig throws error for Machining quality not being recognized

### ISSUE THREAD

**Issue by DrPariah** [pawnishoovy/More-Survivor-Stuff#4]
Machining Rig, the vehicle mounted version, throws errors on startup for unrecognized quality "Machining". Looks like that was included in the earlier versions of the mod, but the current one only has "Lathing" as a tool quality. Unless Machining was added as a quality in the latest experimentals, which is possible.

How to replicate:
-Generate world with More Survivor Stuff mod active
-Create character
-Should see multiple error messages about tool qualities

**Comment by pawnishoovy** [comment]
i have removed the vehicle part entirely as it is obsolete - it wouldn't do anything even with the right quality. at first when i made it, i thought simply giving it the quality would make it work, but it turns out vehicle parts with qualities are actually hardcoded in the game's source. dunno why i didn't remove it then and there but here we are, thanks
